# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0027_auto_20170604_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='cat',
            field=models.BooleanField(choices=[(True, '大鹏种植'), (False, '露天种植')], default=False, verbose_name='大棚或露天种植'),
        ),
        migrations.AlterField(
            model_name='land',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='该块土地可切多少小块'),
        ),
        migrations.AlterField(
            model_name='land',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='land',
            name='desc',
            field=tinymce_4.fields.TinyMCEModelField(default='土地描述', verbose_name='土地描述'),
        ),
        migrations.AlterField(
            model_name='land',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='farm.Farm', verbose_name='农场'),
        ),
        migrations.AlterField(
            model_name='land',
            name='flags',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='标志位'),
        ),
        migrations.AlterField(
            model_name='land',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='该块土地是否可租'),
        ),
        migrations.AlterField(
            model_name='land',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='land',
            name='is_trusteed',
            field=models.BooleanField(default=True, verbose_name='是否托管'),
        ),
        migrations.AlterField(
            model_name='land',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=2999, max_digits=10, verbose_name='每小块土地一年的租金'),
        ),
        migrations.AlterField(
            model_name='land',
            name='item_size',
            field=models.PositiveIntegerField(default=33, verbose_name='每小块土地面积'),
        ),
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='土地名称'),
        ),
        migrations.AlterField(
            model_name='land',
            name='size',
            field=models.PositiveIntegerField(default=666, help_text='单位为平方米', verbose_name='土地面积'),
        ),
        migrations.AlterField(
            model_name='land',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=90.87, max_digits=10, verbose_name='每平方米的租金'),
        ),
        migrations.AlterField(
            model_name='land',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='flags',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='标志位'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='是否被租'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='lands.Land', verbose_name='所属土地'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='notice',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='通知'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='num',
            field=models.CharField(max_length=12, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2999.99, max_digits=10, verbose_name='每年租金'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='size',
            field=models.PositiveIntegerField(default=33, verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
